apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: IntelClusterTemplate
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-intel
    app.kubernetes.io/managed-by: kustomize
  name: intelclustertemplate-sample
spec:
  # TODO(user): Add fields here
