# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "intel-infra-provider.fullname" . }}-manager
  labels:
    {{- include "intel-infra-provider.managerLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.manager.replicaCount }}
  selector:
    matchLabels:
      {{- include "intel-infra-provider.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.manager.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "intel-infra-provider.managerPodLabels" . | nindent 8 }}
    spec:
      {{- with .Values.manager.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "intel-infra-provider.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.manager.podSecurityContext | nindent 8 }}
      containers:
        - name: intel-infra-provider-manager
          securityContext:
            {{- toYaml .Values.manager.securityContext | nindent 12 }}
          image: "localhost:5000/manager:1.1.1-dev-1"
          imagePullPolicy: {{ .Values.manager.image.pullPolicy }}
          command:
            - /manager
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
            {{- if .Values.metrics.service.enabled }}
            - --metrics-bind-address=:{{ .Values.metrics.service.port }}
            - --metrics-secure=false
            {{- end }}
            - --inventory-endpoint={{ .Values.manager.inventory.endpoint }}
            {{- range $key, $value := .Values.manager.extraArgs }}
            - --{{ $key }}={{ $value }}
            {{- end }}
          env:
          {{- with .Values.manager.extraEnv }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            {{- if .Values.metrics.service.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.service.port }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.manager.resources | nindent 12 }}
      {{- with .Values.manager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.manager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.manager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.manager.terminationGracePeriodSeconds }}
