# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.metrics.networkPolicy.enabled -}}
# This NetworkPolicy allows ingress traffic
# with Pods running on namespaces labeled with 'metrics: enabled'. Only Pods on those
# namespaces are able to gathering data from the metrics endpoint.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "intel-infra-provider.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "intel-infra-provider.networkPolicyLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "intel-infra-provider.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    # This allows ingress traffic from any namespace with the label metrics: enabled
    - from:
      - namespaceSelector:
          matchLabels:
            metrics: enabled  # Only from namespaces with this label
      ports:
        - port: {{ .Values.metrics.service.port }}
          protocol: TCP
{{- end -}}
