// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: cluster_orchestrator_southbound.proto

package cluster_orchestrator_southbound

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterClusterResponse_Result int32

const (
	RegisterClusterResponse_SUCCESS RegisterClusterResponse_Result = 0
	RegisterClusterResponse_ERROR   RegisterClusterResponse_Result = 1
)

// Enum value maps for RegisterClusterResponse_Result.
var (
	RegisterClusterResponse_Result_name = map[int32]string{
		0: "SUCCESS",
		1: "ERROR",
	}
	RegisterClusterResponse_Result_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   1,
	}
)

func (x RegisterClusterResponse_Result) Enum() *RegisterClusterResponse_Result {
	p := new(RegisterClusterResponse_Result)
	*p = x
	return p
}

func (x RegisterClusterResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterClusterResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_cluster_orchestrator_southbound_proto_enumTypes[0].Descriptor()
}

func (RegisterClusterResponse_Result) Type() protoreflect.EnumType {
	return &file_cluster_orchestrator_southbound_proto_enumTypes[0]
}

func (x RegisterClusterResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterClusterResponse_Result.Descriptor instead.
func (RegisterClusterResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_cluster_orchestrator_southbound_proto_rawDescGZIP(), []int{1, 0}
}

type UpdateClusterStatusRequest_Code int32

const (
	UpdateClusterStatusRequest_INACTIVE              UpdateClusterStatusRequest_Code = 0
	UpdateClusterStatusRequest_REGISTERING           UpdateClusterStatusRequest_Code = 1
	UpdateClusterStatusRequest_INSTALL_IN_PROGRESS   UpdateClusterStatusRequest_Code = 2
	UpdateClusterStatusRequest_ACTIVE                UpdateClusterStatusRequest_Code = 3
	UpdateClusterStatusRequest_DEREGISTERING         UpdateClusterStatusRequest_Code = 4
	UpdateClusterStatusRequest_UNINSTALL_IN_PROGRESS UpdateClusterStatusRequest_Code = 5
	UpdateClusterStatusRequest_ERROR                 UpdateClusterStatusRequest_Code = 6
)

// Enum value maps for UpdateClusterStatusRequest_Code.
var (
	UpdateClusterStatusRequest_Code_name = map[int32]string{
		0: "INACTIVE",
		1: "REGISTERING",
		2: "INSTALL_IN_PROGRESS",
		3: "ACTIVE",
		4: "DEREGISTERING",
		5: "UNINSTALL_IN_PROGRESS",
		6: "ERROR",
	}
	UpdateClusterStatusRequest_Code_value = map[string]int32{
		"INACTIVE":              0,
		"REGISTERING":           1,
		"INSTALL_IN_PROGRESS":   2,
		"ACTIVE":                3,
		"DEREGISTERING":         4,
		"UNINSTALL_IN_PROGRESS": 5,
		"ERROR":                 6,
	}
)

func (x UpdateClusterStatusRequest_Code) Enum() *UpdateClusterStatusRequest_Code {
	p := new(UpdateClusterStatusRequest_Code)
	*p = x
	return p
}

func (x UpdateClusterStatusRequest_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateClusterStatusRequest_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_cluster_orchestrator_southbound_proto_enumTypes[1].Descriptor()
}

func (UpdateClusterStatusRequest_Code) Type() protoreflect.EnumType {
	return &file_cluster_orchestrator_southbound_proto_enumTypes[1]
}

func (x UpdateClusterStatusRequest_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateClusterStatusRequest_Code.Descriptor instead.
func (UpdateClusterStatusRequest_Code) EnumDescriptor() ([]byte, []int) {
	return file_cluster_orchestrator_southbound_proto_rawDescGZIP(), []int{3, 0}
}

type UpdateClusterStatusResponse_ActionRequest int32

const (
	UpdateClusterStatusResponse_NONE       UpdateClusterStatusResponse_ActionRequest = 0
	UpdateClusterStatusResponse_REGISTER   UpdateClusterStatusResponse_ActionRequest = 1
	UpdateClusterStatusResponse_DEREGISTER UpdateClusterStatusResponse_ActionRequest = 2
)

// Enum value maps for UpdateClusterStatusResponse_ActionRequest.
var (
	UpdateClusterStatusResponse_ActionRequest_name = map[int32]string{
		0: "NONE",
		1: "REGISTER",
		2: "DEREGISTER",
	}
	UpdateClusterStatusResponse_ActionRequest_value = map[string]int32{
		"NONE":       0,
		"REGISTER":   1,
		"DEREGISTER": 2,
	}
)

func (x UpdateClusterStatusResponse_ActionRequest) Enum() *UpdateClusterStatusResponse_ActionRequest {
	p := new(UpdateClusterStatusResponse_ActionRequest)
	*p = x
	return p
}

func (x UpdateClusterStatusResponse_ActionRequest) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateClusterStatusResponse_ActionRequest) Descriptor() protoreflect.EnumDescriptor {
	return file_cluster_orchestrator_southbound_proto_enumTypes[2].Descriptor()
}

func (UpdateClusterStatusResponse_ActionRequest) Type() protoreflect.EnumType {
	return &file_cluster_orchestrator_southbound_proto_enumTypes[2]
}

func (x UpdateClusterStatusResponse_ActionRequest) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateClusterStatusResponse_ActionRequest.Descriptor instead.
func (UpdateClusterStatusResponse_ActionRequest) EnumDescriptor() ([]byte, []int) {
	return file_cluster_orchestrator_southbound_proto_rawDescGZIP(), []int{4, 0}
}

type GetClusterNumByTemplateIdentifierResponse_Result int32

const (
	GetClusterNumByTemplateIdentifierResponse_SUCCESS GetClusterNumByTemplateIdentifierResponse_Result = 0
	GetClusterNumByTemplateIdentifierResponse_ERROR   GetClusterNumByTemplateIdentifierResponse_Result = 1
)

// Enum value maps for GetClusterNumByTemplateIdentifierResponse_Result.
var (
	GetClusterNumByTemplateIdentifierResponse_Result_name = map[int32]string{
		0: "SUCCESS",
		1: "ERROR",
	}
	GetClusterNumByTemplateIdentifierResponse_Result_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   1,
	}
)

func (x GetClusterNumByTemplateIdentifierResponse_Result) Enum() *GetClusterNumByTemplateIdentifierResponse_Result {
	p := new(GetClusterNumByTemplateIdentifierResponse_Result)
	*p = x
	return p
}

func (x GetClusterNumByTemplateIdentifierResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetClusterNumByTemplateIdentifierResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_cluster_orchestrator_southbound_proto_enumTypes[3].Descriptor()
}

func (GetClusterNumByTemplateIdentifierResponse_Result) Type() protoreflect.EnumType {
	return &file_cluster_orchestrator_southbound_proto_enumTypes[3]
}

func (x GetClusterNumByTemplateIdentifierResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetClusterNumByTemplateIdentifierResponse_Result.Descriptor instead.
func (GetClusterNumByTemplateIdentifierResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_cluster_orchestrator_southbound_proto_rawDescGZIP(), []int{6, 0}
}

// RegisterClusterRequest contains Edge Node identity assigned by Inventory
type RegisterClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeGuid      string                 `protobuf:"bytes,1,opt,name=node_guid,json=nodeGuid,proto3" json:"node_guid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterClusterRequest) Reset() {
	*x = RegisterClusterRequest{}
	mi := &file_cluster_orchestrator_southbound_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClusterRequest) ProtoMessage() {}

func (x *RegisterClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_orchestrator_southbound_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClusterRequest.ProtoReflect.Descriptor instead.
func (*RegisterClusterRequest) Descriptor() ([]byte, []int) {
	return file_cluster_orchestrator_southbound_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterClusterRequest) GetNodeGuid() string {
	if x != nil {
		return x.NodeGuid
	}
	return ""
}

// RegisterClusterResponse contains shell script to be executed by Cluster Agent to install cluster
type RegisterClusterResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	InstallCmd    *ShellScriptCommand            `protobuf:"bytes,1,opt,name=install_cmd,json=installCmd,proto3" json:"install_cmd,omitempty"`
	UninstallCmd  *ShellScriptCommand            `protobuf:"bytes,2,opt,name=uninstall_cmd,json=uninstallCmd,proto3" json:"uninstall_cmd,omitempty"`
	Res           RegisterClusterResponse_Result `protobuf:"varint,3,opt,name=res,proto3,enum=cluster_orchestrator_southbound_proto.RegisterClusterResponse_Result" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterClusterResponse) Reset() {
	*x = RegisterClusterResponse{}
	mi := &file_cluster_orchestrator_southbound_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClusterResponse) ProtoMessage() {}

func (x *RegisterClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_orchestrator_southbound_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClusterResponse.ProtoReflect.Descriptor instead.
func (*RegisterClusterResponse) Descriptor() ([]byte, []int) {
	return file_cluster_orchestrator_southbound_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterClusterResponse) GetInstallCmd() *ShellScriptCommand {
	if x != nil {
		return x.InstallCmd
	}
	return nil
}

func (x *RegisterClusterResponse) GetUninstallCmd() *ShellScriptCommand {
	if x != nil {
		return x.UninstallCmd
	}
	return nil
}

func (x *RegisterClusterResponse) GetRes() RegisterClusterResponse_Result {
	if x != nil {
		return x.Res
	}
	return RegisterClusterResponse_SUCCESS
}

// ShellScriptCommand is a command to be executed by Cluster Agent to install/uninstall LKPE.
// command is to be executed in shell, like this `sh -c command`
type ShellScriptCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// example1: "curl -fL https://DOMAIN.NAME/system-agent-install.sh | sudo  sh -s - --server https://DOMAIN.NAME --label 'cattle.io/os=linux' --token 86f9cqfnvvlmwmvvmsptmr5wqj9d6bqpxkmxbvjw2txklhbglcdtff --ca-checksum b50da8bfa2cbcc13e209b9ffbab4b39c699e0aa2b3fe50f44ec4477c54725ea3 --etcd --controlplane --worker"
	// example2: "/usr/local/bin/rancher-system-agent-uninstall.sh; /usr/local/bin/rke2-uninstall.sh"
	Command       string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellScriptCommand) Reset() {
	*x = ShellScriptCommand{}
	mi := &file_cluster_orchestrator_southbound_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellScriptCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellScriptCommand) ProtoMessage() {}

func (x *ShellScriptCommand) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_orchestrator_southbound_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellScriptCommand.ProtoReflect.Descriptor instead.
func (*ShellScriptCommand) Descriptor() ([]byte, []int) {
	return file_cluster_orchestrator_southbound_proto_rawDescGZIP(), []int{2}
}

func (x *ShellScriptCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// UpdateClusterStatusRequest is used by Cluster Agent to represent its internal state machine
type UpdateClusterStatusRequest struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Code          UpdateClusterStatusRequest_Code `protobuf:"varint,1,opt,name=code,proto3,enum=cluster_orchestrator_southbound_proto.UpdateClusterStatusRequest_Code" json:"code,omitempty"`
	NodeGuid      string                          `protobuf:"bytes,2,opt,name=node_guid,json=nodeGuid,proto3" json:"node_guid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClusterStatusRequest) Reset() {
	*x = UpdateClusterStatusRequest{}
	mi := &file_cluster_orchestrator_southbound_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClusterStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClusterStatusRequest) ProtoMessage() {}

func (x *UpdateClusterStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_orchestrator_southbound_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClusterStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateClusterStatusRequest) Descriptor() ([]byte, []int) {
	return file_cluster_orchestrator_southbound_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateClusterStatusRequest) GetCode() UpdateClusterStatusRequest_Code {
	if x != nil {
		return x.Code
	}
	return UpdateClusterStatusRequest_INACTIVE
}

func (x *UpdateClusterStatusRequest) GetNodeGuid() string {
	if x != nil {
		return x.NodeGuid
	}
	return ""
}

// UpdateClusterStatusResponse is used to request Cluster Agent to transition to new internal state
type UpdateClusterStatusResponse struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	ActionRequest UpdateClusterStatusResponse_ActionRequest `protobuf:"varint,1,opt,name=action_request,json=actionRequest,proto3,enum=cluster_orchestrator_southbound_proto.UpdateClusterStatusResponse_ActionRequest" json:"action_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClusterStatusResponse) Reset() {
	*x = UpdateClusterStatusResponse{}
	mi := &file_cluster_orchestrator_southbound_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClusterStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClusterStatusResponse) ProtoMessage() {}

func (x *UpdateClusterStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_orchestrator_southbound_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClusterStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateClusterStatusResponse) Descriptor() ([]byte, []int) {
	return file_cluster_orchestrator_southbound_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateClusterStatusResponse) GetActionRequest() UpdateClusterStatusResponse_ActionRequest {
	if x != nil {
		return x.ActionRequest
	}
	return UpdateClusterStatusResponse_NONE
}

type GetClusterNumByTemplateIdentifierRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// it's format is "template name" + "-" + "template version"
	TemplateIdentifier string `protobuf:"bytes,1,opt,name=templateIdentifier,proto3" json:"templateIdentifier,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetClusterNumByTemplateIdentifierRequest) Reset() {
	*x = GetClusterNumByTemplateIdentifierRequest{}
	mi := &file_cluster_orchestrator_southbound_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterNumByTemplateIdentifierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterNumByTemplateIdentifierRequest) ProtoMessage() {}

func (x *GetClusterNumByTemplateIdentifierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_orchestrator_southbound_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterNumByTemplateIdentifierRequest.ProtoReflect.Descriptor instead.
func (*GetClusterNumByTemplateIdentifierRequest) Descriptor() ([]byte, []int) {
	return file_cluster_orchestrator_southbound_proto_rawDescGZIP(), []int{5}
}

func (x *GetClusterNumByTemplateIdentifierRequest) GetTemplateIdentifier() string {
	if x != nil {
		return x.TemplateIdentifier
	}
	return ""
}

type GetClusterNumByTemplateIdentifierResponse struct {
	state         protoimpl.MessageState                           `protogen:"open.v1"`
	Res           GetClusterNumByTemplateIdentifierResponse_Result `protobuf:"varint,1,opt,name=res,proto3,enum=cluster_orchestrator_southbound_proto.GetClusterNumByTemplateIdentifierResponse_Result" json:"res,omitempty"`
	ClusterNum    int32                                            `protobuf:"varint,2,opt,name=clusterNum,proto3" json:"clusterNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterNumByTemplateIdentifierResponse) Reset() {
	*x = GetClusterNumByTemplateIdentifierResponse{}
	mi := &file_cluster_orchestrator_southbound_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterNumByTemplateIdentifierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterNumByTemplateIdentifierResponse) ProtoMessage() {}

func (x *GetClusterNumByTemplateIdentifierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_orchestrator_southbound_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterNumByTemplateIdentifierResponse.ProtoReflect.Descriptor instead.
func (*GetClusterNumByTemplateIdentifierResponse) Descriptor() ([]byte, []int) {
	return file_cluster_orchestrator_southbound_proto_rawDescGZIP(), []int{6}
}

func (x *GetClusterNumByTemplateIdentifierResponse) GetRes() GetClusterNumByTemplateIdentifierResponse_Result {
	if x != nil {
		return x.Res
	}
	return GetClusterNumByTemplateIdentifierResponse_SUCCESS
}

func (x *GetClusterNumByTemplateIdentifierResponse) GetClusterNum() int32 {
	if x != nil {
		return x.ClusterNum
	}
	return 0
}

var File_cluster_orchestrator_southbound_proto protoreflect.FileDescriptor

const file_cluster_orchestrator_southbound_proto_rawDesc = "" +
	"\n" +
	"%cluster_orchestrator_southbound.proto\x12%cluster_orchestrator_southbound_proto\x1a\x17validate/validate.proto\"z\n" +
	"\x16RegisterClusterRequest\x12`\n" +
	"\tnode_guid\x18\x01 \x01(\tBC\xfaB@r>2<^[{]?[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}[}]?$R\bnodeGuid\"\xd0\x02\n" +
	"\x17RegisterClusterResponse\x12Z\n" +
	"\vinstall_cmd\x18\x01 \x01(\v29.cluster_orchestrator_southbound_proto.ShellScriptCommandR\n" +
	"installCmd\x12^\n" +
	"\runinstall_cmd\x18\x02 \x01(\v29.cluster_orchestrator_southbound_proto.ShellScriptCommandR\funinstallCmd\x12W\n" +
	"\x03res\x18\x03 \x01(\x0e2E.cluster_orchestrator_southbound_proto.RegisterClusterResponse.ResultR\x03res\" \n" +
	"\x06Result\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01\".\n" +
	"\x12ShellScriptCommand\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"\xe0\x02\n" +
	"\x1aUpdateClusterStatusRequest\x12Z\n" +
	"\x04code\x18\x01 \x01(\x0e2F.cluster_orchestrator_southbound_proto.UpdateClusterStatusRequest.CodeR\x04code\x12`\n" +
	"\tnode_guid\x18\x02 \x01(\tBC\xfaB@r>2<^[{]?[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}[}]?$R\bnodeGuid\"\x83\x01\n" +
	"\x04Code\x12\f\n" +
	"\bINACTIVE\x10\x00\x12\x0f\n" +
	"\vREGISTERING\x10\x01\x12\x17\n" +
	"\x13INSTALL_IN_PROGRESS\x10\x02\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x03\x12\x11\n" +
	"\rDEREGISTERING\x10\x04\x12\x19\n" +
	"\x15UNINSTALL_IN_PROGRESS\x10\x05\x12\t\n" +
	"\x05ERROR\x10\x06\"\xcf\x01\n" +
	"\x1bUpdateClusterStatusResponse\x12w\n" +
	"\x0eaction_request\x18\x01 \x01(\x0e2P.cluster_orchestrator_southbound_proto.UpdateClusterStatusResponse.ActionRequestR\ractionRequest\"7\n" +
	"\rActionRequest\x12\b\n" +
	"\x04NONE\x10\x00\x12\f\n" +
	"\bREGISTER\x10\x01\x12\x0e\n" +
	"\n" +
	"DEREGISTER\x10\x02\"Z\n" +
	"(GetClusterNumByTemplateIdentifierRequest\x12.\n" +
	"\x12templateIdentifier\x18\x01 \x01(\tR\x12templateIdentifier\"\xd8\x01\n" +
	")GetClusterNumByTemplateIdentifierResponse\x12i\n" +
	"\x03res\x18\x01 \x01(\x0e2W.cluster_orchestrator_southbound_proto.GetClusterNumByTemplateIdentifierResponse.ResultR\x03res\x12\x1e\n" +
	"\n" +
	"clusterNum\x18\x02 \x01(\x05R\n" +
	"clusterNum\" \n" +
	"\x06Result\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x012\xa0\x04\n" +
	"\x1dClusterOrchestratorSouthbound\x12\x92\x01\n" +
	"\x0fRegisterCluster\x12=.cluster_orchestrator_southbound_proto.RegisterClusterRequest\x1a>.cluster_orchestrator_southbound_proto.RegisterClusterResponse\"\x00\x12\x9e\x01\n" +
	"\x13UpdateClusterStatus\x12A.cluster_orchestrator_southbound_proto.UpdateClusterStatusRequest\x1aB.cluster_orchestrator_southbound_proto.UpdateClusterStatusResponse\"\x00\x12\xc8\x01\n" +
	"!GetClusterNumByTemplateIdentifier\x12O.cluster_orchestrator_southbound_proto.GetClusterNumByTemplateIdentifierRequest\x1aP.cluster_orchestrator_southbound_proto.GetClusterNumByTemplateIdentifierResponse\"\x00B#Z!.;cluster_orchestrator_southboundb\x06proto3"

var (
	file_cluster_orchestrator_southbound_proto_rawDescOnce sync.Once
	file_cluster_orchestrator_southbound_proto_rawDescData []byte
)

func file_cluster_orchestrator_southbound_proto_rawDescGZIP() []byte {
	file_cluster_orchestrator_southbound_proto_rawDescOnce.Do(func() {
		file_cluster_orchestrator_southbound_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_orchestrator_southbound_proto_rawDesc), len(file_cluster_orchestrator_southbound_proto_rawDesc)))
	})
	return file_cluster_orchestrator_southbound_proto_rawDescData
}

var file_cluster_orchestrator_southbound_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_cluster_orchestrator_southbound_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cluster_orchestrator_southbound_proto_goTypes = []any{
	(RegisterClusterResponse_Result)(0),                   // 0: cluster_orchestrator_southbound_proto.RegisterClusterResponse.Result
	(UpdateClusterStatusRequest_Code)(0),                  // 1: cluster_orchestrator_southbound_proto.UpdateClusterStatusRequest.Code
	(UpdateClusterStatusResponse_ActionRequest)(0),        // 2: cluster_orchestrator_southbound_proto.UpdateClusterStatusResponse.ActionRequest
	(GetClusterNumByTemplateIdentifierResponse_Result)(0), // 3: cluster_orchestrator_southbound_proto.GetClusterNumByTemplateIdentifierResponse.Result
	(*RegisterClusterRequest)(nil),                        // 4: cluster_orchestrator_southbound_proto.RegisterClusterRequest
	(*RegisterClusterResponse)(nil),                       // 5: cluster_orchestrator_southbound_proto.RegisterClusterResponse
	(*ShellScriptCommand)(nil),                            // 6: cluster_orchestrator_southbound_proto.ShellScriptCommand
	(*UpdateClusterStatusRequest)(nil),                    // 7: cluster_orchestrator_southbound_proto.UpdateClusterStatusRequest
	(*UpdateClusterStatusResponse)(nil),                   // 8: cluster_orchestrator_southbound_proto.UpdateClusterStatusResponse
	(*GetClusterNumByTemplateIdentifierRequest)(nil),      // 9: cluster_orchestrator_southbound_proto.GetClusterNumByTemplateIdentifierRequest
	(*GetClusterNumByTemplateIdentifierResponse)(nil),     // 10: cluster_orchestrator_southbound_proto.GetClusterNumByTemplateIdentifierResponse
}
var file_cluster_orchestrator_southbound_proto_depIdxs = []int32{
	6,  // 0: cluster_orchestrator_southbound_proto.RegisterClusterResponse.install_cmd:type_name -> cluster_orchestrator_southbound_proto.ShellScriptCommand
	6,  // 1: cluster_orchestrator_southbound_proto.RegisterClusterResponse.uninstall_cmd:type_name -> cluster_orchestrator_southbound_proto.ShellScriptCommand
	0,  // 2: cluster_orchestrator_southbound_proto.RegisterClusterResponse.res:type_name -> cluster_orchestrator_southbound_proto.RegisterClusterResponse.Result
	1,  // 3: cluster_orchestrator_southbound_proto.UpdateClusterStatusRequest.code:type_name -> cluster_orchestrator_southbound_proto.UpdateClusterStatusRequest.Code
	2,  // 4: cluster_orchestrator_southbound_proto.UpdateClusterStatusResponse.action_request:type_name -> cluster_orchestrator_southbound_proto.UpdateClusterStatusResponse.ActionRequest
	3,  // 5: cluster_orchestrator_southbound_proto.GetClusterNumByTemplateIdentifierResponse.res:type_name -> cluster_orchestrator_southbound_proto.GetClusterNumByTemplateIdentifierResponse.Result
	4,  // 6: cluster_orchestrator_southbound_proto.ClusterOrchestratorSouthbound.RegisterCluster:input_type -> cluster_orchestrator_southbound_proto.RegisterClusterRequest
	7,  // 7: cluster_orchestrator_southbound_proto.ClusterOrchestratorSouthbound.UpdateClusterStatus:input_type -> cluster_orchestrator_southbound_proto.UpdateClusterStatusRequest
	9,  // 8: cluster_orchestrator_southbound_proto.ClusterOrchestratorSouthbound.GetClusterNumByTemplateIdentifier:input_type -> cluster_orchestrator_southbound_proto.GetClusterNumByTemplateIdentifierRequest
	5,  // 9: cluster_orchestrator_southbound_proto.ClusterOrchestratorSouthbound.RegisterCluster:output_type -> cluster_orchestrator_southbound_proto.RegisterClusterResponse
	8,  // 10: cluster_orchestrator_southbound_proto.ClusterOrchestratorSouthbound.UpdateClusterStatus:output_type -> cluster_orchestrator_southbound_proto.UpdateClusterStatusResponse
	10, // 11: cluster_orchestrator_southbound_proto.ClusterOrchestratorSouthbound.GetClusterNumByTemplateIdentifier:output_type -> cluster_orchestrator_southbound_proto.GetClusterNumByTemplateIdentifierResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_cluster_orchestrator_southbound_proto_init() }
func file_cluster_orchestrator_southbound_proto_init() {
	if File_cluster_orchestrator_southbound_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_orchestrator_southbound_proto_rawDesc), len(file_cluster_orchestrator_southbound_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cluster_orchestrator_southbound_proto_goTypes,
		DependencyIndexes: file_cluster_orchestrator_southbound_proto_depIdxs,
		EnumInfos:         file_cluster_orchestrator_southbound_proto_enumTypes,
		MessageInfos:      file_cluster_orchestrator_southbound_proto_msgTypes,
	}.Build()
	File_cluster_orchestrator_southbound_proto = out.File
	file_cluster_orchestrator_southbound_proto_goTypes = nil
	file_cluster_orchestrator_southbound_proto_depIdxs = nil
}
