# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---

name: Pre-Merge CI Pipeline

on:
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch: 

permissions: {}

jobs:
  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        persist-credentials: false

    - name: "Setup"
      uses: open-edge-platform/orch-ci/.github/actions/bootstrap@main
      with:
        gh_token: ${{ secrets.SYS_ORCH_GITHUB }}
        bootstrap_tools: "go,gotools,nodejs"

    - name: Lint code
      run: make lint

  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        persist-credentials: false

    - name: "Setup"
      uses: open-edge-platform/orch-ci/.github/actions/bootstrap@main
      with:
        gh_token: ${{ secrets.SYS_ORCH_GITHUB }}
        bootstrap_tools: "go,gotools"

    - name: Build code
      run: make build

  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        persist-credentials: false

    - name: "Setup"
      uses: open-edge-platform/orch-ci/.github/actions/bootstrap@main
      with:
        gh_token: ${{ secrets.SYS_ORCH_GITHUB }}
        bootstrap_tools: "go,gotools" 

    - name: Test code
      run: make test
  
  pre-merge:
    permissions:
      contents: read
    needs: [lint, build, test]
    uses: open-edge-platform/orch-ci/.github/workflows/pre-merge.yml@0.1.42
    with:
      bootstrap_tools: "base,go"
      cache_go: true
      remove_cache_go: true
      run_security_scans: true
      run_version_check: true
      run_dep_version_check: true
      run_build: false
      run_lint: false
      run_test: false
      run_validate_clean_folder: false
      run_docker_build: true
      run_docker_push: false
      run_helm_build: true
      run_helm_push: false
      run_artifact: false
      version_suffix: "-pr-${{ github.event.number }}"
    secrets: inherit  # zizmor: ignore[secrets-inherit]
